# Generated by Django 6.0.2 on 2026-02-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_entered', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.event')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='templates/')),
                ('mode', models.CharField(choices=[('coords', 'Escribir por coordenadas'), ('field', 'Campo rellenable (PDF Form Field)')], default='coords', max_length=10)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField(default=100)),
                ('y', models.FloatField(default=300)),
                ('font_size', models.FloatField(default=28)),
                ('align', models.CharField(default='center', max_length=10)),
                ('field_name', models.CharField(blank=True, default='full_name', max_length=100)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificados.event')),
            ],
        ),
    ]
