# Generated by Django 6.0.5 on 2026-05-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_downloadlog_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('full_name_normalized', models.CharField(db_index=True, max_length=200)),
                ('email_normalized', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='certificados.event')),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'email_normalized'), name='unique_event_email')],
            },
        ),
    ]
