# Generated by Django 6.0.5 on 2026-05-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info_text',
            field=models.TextField(blank=True, default='', help_text='Texto informativo que se muestra en la página pública del evento, debajo del email.'),
        ),
        migrations.AddField(
            model_name='event',
            name='require_email',
            field=models.BooleanField(default=True, help_text='Si está activado, el form pide email obligatorio y, si hay inscriptos cargados, valida nombre+email contra la lista.'),
        ),
    ]
