# Generated by Django 6.0.5 on 2026-05-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_event_info_text_event_require_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='certificados.attendee'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='email_normalized',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='RejectedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_entered', models.CharField(blank=True, default='', max_length=200)),
                ('email_entered', models.EmailField(blank=True, default='', max_length=254)),
                ('reason', models.CharField(choices=[('not_in_list', 'No está en la lista de inscriptos'), ('duplicate', 'Certificado ya descargado'), ('missing_email', 'Email no ingresado'), ('missing_name', 'Nombre no ingresado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_attempts', to='certificados.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
