# Generated by Django 6.0.5 on 2026-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_downloadlog_attendee_downloadlog_email_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='max_width',
            field=models.FloatField(default=0),
        ),
    ]
