# Generated by Django 6.0.5 on 2026-06-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_certificatetemplate_max_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='valign',
            field=models.CharField(default='baseline', max_length=10),
        ),
    ]
