# Generated by Django 6.0.5 on 2026-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0007_certificatetemplate_valign'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='download_limit',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas descargas públicas puede hacer la misma persona antes de bloquearse. 0 = sin límite.'),
        ),
        migrations.AddField(
            model_name='event',
            name='duplicate_message',
            field=models.TextField(blank=True, default='', help_text='Mensaje que se muestra cuando la persona alcanza el límite de descargas. Vacío = texto por defecto.'),
        ),
    ]
