# Generated by Django 6.0.5 on 2026-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0008_event_download_limit_event_duplicate_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo', models.CharField(default='#ffffff', help_text='Color de fondo de las páginas públicas (hex, ej: #ffffff).', max_length=7)),
                ('color_mensaje', models.CharField(default='#1d4ed8', help_text='Color del título y el mensaje principal (hex, ej: #1d4ed8).', max_length=7)),
                ('titulo', models.CharField(default='Descargar certificado', help_text='Título que se muestra en la página de inicio.', max_length=120)),
                ('mensaje', models.TextField(blank=True, default='Seleccionar el evento e ingresar el nombre completo y el email para descargar el certificado de participación.', help_text='Mensaje/instrucción debajo del título en la página de inicio.')),
                ('mantenimiento', models.BooleanField(default=False, help_text='Si está activado, el sitio público muestra el mensaje de mantenimiento. El panel sigue accesible.')),
                ('mensaje_mantenimiento', models.TextField(blank=True, default='Estamos recibiendo muchas visitas en este momento. Volver a intentar en unos minutos.', help_text='Mensaje que se muestra cuando el modo mantenimiento está activo.')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
