# Generated by Django 6.0.7 on 2026-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_download',
            field=models.BooleanField(default=False, help_text='Si está activado, cualquier persona puede descargar aunque no esté en la lista de inscriptos (descarga libre).'),
        ),
    ]
