# Generated by Django 6.0.5 on 2026-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0012_suspiciousattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
