# Generated by Django 6.0.5 on 2026-09-08 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0013_downloadlog_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mail_body',
            field=models.TextField(default='Hola {nombre},\n\nAdjuntamos tu certificado de participación en el {evento}.\n\nGuardalo en tu dispositivo. Ante cualquier consulta, responder este correo.\n\nBrisa Enfermeros', help_text='Texto del correo (texto plano). Variables: {nombre}, {evento}.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_from_email',
            field=models.EmailField(blank=True, default='', help_text='Casilla remitente. Vacío = la casilla configurada en el servidor (EMAIL_HOST_USER).', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_from_name',
            field=models.CharField(default='Brisa Enfermeros', help_text='Nombre visible del remitente.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_reply_to',
            field=models.EmailField(blank=True, default='', help_text='A dónde llegan las respuestas. Vacío = el remitente.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_subject',
            field=models.CharField(default='Tu certificado del {evento}', help_text='Asunto. Variables: {nombre}, {evento}.', max_length=200),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('superseded', 'Reemplazado')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='certificados.attendee')),
                ('download_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificados.downloadlog')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='certificados.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='certificado_status_6506e8_idx')],
            },
        ),
    ]
