# Generated by Django 6.0.5 on 2026-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0014_emaildelivery_sitesettings_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='test_for_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_test_recipients',
            field=models.TextField(blank=True, default='', help_text='Casillas que reciben el correo cuando el formulario se usa con la sesión del panel iniciada (modo prueba). Separadas por coma o renglón.'),
        ),
    ]
