# Generated by Django 6.0.5 on 2026-10-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0015_modo_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='Modo prueba para todos: no se registran descargas ni rechazos y el correo va a las casillas de prueba, no al inscripto. Apagarlo antes del evento real.'),
        ),
    ]
